// USER LOGIN TYPES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// GET USER
export const USER_LOADED = 'USER_LOADED'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'
// IS USER AUTHENTICATED TYPES

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

// USER LOGOUT
export const LOGOUT = 'LOGOUT'
