// USER LOGIN TYPES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// User Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

// USER ACTIVATION
export const ACTIVATION_SUCCESS = 'ACTIVATIOM_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL'

// GET USER
export const USER_LOADED = 'USER_LOADED'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'
// IS USER AUTHENTICATED TYPES

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

// USER LOGOUT
export const LOGOUT = 'LOGOUT'

// PASSWORD RESET TYPES
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL'
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS'
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL'

// GOOGLE LOGIN
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS'
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL'

// FACEBOOK LOGIN
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS'
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL'